Learn numpy basic

In [1]:
import numpy as np

Creating array from list

In [4]:
arr_1d = np.array([1,2,3])
print("1D array:",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)



1D array: [1 2 3]
2D array: [[1 2 3]
 [4 5 6]]


List Vs NumPy array

In [6]:
py_list = [1,2,3] #The elements themselves are not multiplied; the entire list is replicated.
print("Python list Multiplication: ", py_list * 2)

np_array = np.array([1,2,3]) #Element themselves multiplied
print("Python list Multiplication: ", np_array * 2)

Python list Multiplication:  [1, 2, 3, 1, 2, 3]
Python list Multiplication:  [2 4 6]


In [7]:
import time

start = time.time()
py_list = [i*2 for i in range(100000)]
print("list operation time: ", time.time() - start)

# arange() in numpy allow us to create array
start = time.time()
ar_numpy = np.arange(100000) * 2
print("list operation time: ", time.time() - start)

list operation time:  0.015990257263183594
list operation time:  0.0009996891021728516


Creating array from scartch

In [22]:
# zero matrics
zeros = np.zeros((3,3))
print("Zero Matrix:\n",zeros)

#ones matrix
ones = np.ones((3,3))
print("Identity Matrix:\n",ones)

#full
full = np.full((3,3),5)
print("Full Matrix:\n",full)

#random matrix
random = np.random.random((3,3))
print("Random Matrix:\n",random)

## note
# Generate a 3x3 matrix of random floats between 0 and 1
float_matrix = np.random.rand(3, 3)

# Convert to integers (0 or 1) by thresholding
int_matrix = (float_matrix > 0.5).astype(int)
print(int_matrix)

random = np.random.randint(0,10,(3,3))
print("Random Matrix:\n",random)

#sequence

sequence = np.arange(0,100,5)
print("Sequence Matrix:\n",sequence)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full Matrix:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Random Matrix:
 [[0.98779919 0.82971155 0.23192444]
 [0.10856736 0.69588549 0.8243819 ]
 [0.87537661 0.08025739 0.01780839]]
[[0 0 0]
 [1 1 1]
 [1 0 1]]
Random Matrix:
 [[8 5 9]
 [0 1 6]
 [7 9 1]]
Sequence Matrix:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
