Learn numpy basic

In [2]:
import numpy as np

Creating array from list

In [4]:
arr_1d = np.array([1,2,3])
print("1D array:",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)



1D array: [1 2 3]
2D array: [[1 2 3]
 [4 5 6]]


List Vs NumPy array

In [6]:
py_list = [1,2,3] #The elements themselves are not multiplied; the entire list is replicated.
print("Python list Multiplication: ", py_list * 2)

np_array = np.array([1,2,3]) #Element themselves multiplied
print("Python list Multiplication: ", np_array * 2)

Python list Multiplication:  [1, 2, 3, 1, 2, 3]
Python list Multiplication:  [2 4 6]


In [ ]:
import time

start = time.time()
py_list = [i*2 for i in range(100000)]
print("list operation time: ", time.time() - start)

# arange() in numpy allow us to create array
start = time.time()
ar_numpy = np.arange(100000) * 2
print("Numpy array operation time: ", time.time() - start)

list operation time:  0.2352912425994873
Numpy array operation time:  0.005133152008056641


Creating array from scartch

In [31]:
# zero matrics
zeros = np.zeros((3,3))
print("Zero Matrix:\n",zeros)

#ones matrix
ones = np.ones((3,3))
print("Identity Matrix:\n",ones)

#full
full = np.full((3,3),5)
print("Full Matrix:\n",full)

#random matrix
random = np.random.random((3,3))
print("Random Matrix:\n",random)

## note
# Generate a 3x3 matrix of random floats between 0 and 1
float_matrix = np.random.rand(3, 3)

# Convert to integers (0 or 1) by thresholding
int_matrix = (float_matrix > 0.5).astype(int)
print(int_matrix)

random = np.random.randint(0,10,(3,3))
print("Random Matrix:\n",random)

#sequence

sequence = np.arange(0,100,5)
print("Sequence Matrix:\n",sequence)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full Matrix:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Random Matrix:
 [[0.58269419 0.37435314 0.72337192]
 [0.17431256 0.93632189 0.10489397]
 [0.81856515 0.50483488 0.61240496]]
[[1 0 1]
 [1 1 0]
 [0 1 1]]
Random Matrix:
 [[5 3 2]
 [3 6 4]
 [3 2 0]]
Sequence Matrix:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


Vector, Matrix and Tensor

In [ ]:
# 1D called vector
vector = np.array([1,2,3])
print("Vector: ", vector)

#2D called matrix
matrix = np.array([[1,2],
                   [3,4]])
print("Matrix: ", matrix)

#multi dimension called Tensor
tensor = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2]
 [3 4]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [27]:
np_array = np.array([[1,2,3],
                     [4,5,6]])
print("Shape: ", np_array.shape)
print("Dimension: ", np_array.ndim)
print("Size: ", np_array.size) # tell the total no of elements in array
print("DType: ", np_array.dtype) # tell the type of elements in array

Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64


Array Shaping

In [29]:
#original array
original_array = np.arange(1,17)
print("Original Array:", original_array)

#reshape array
reshape = original_array.reshape((4,4))
print("\nReshape Array: \n", reshape)

#flatten function convert multi dimensional array into 1D
#Always gives you a copy. If you modify the result of flatten(), 
# the original array stays untouched because it’s a separate piece of data.
flatten = reshape.flatten()
print("\nFlatten Array:", flatten)

#ravel function convert multi dimensional array into 1D
#ravel does not change the original array, it just returns the 
#view of that array in 1D, but when we make changes in the returned array, the original array changes.
ravel = reshape.ravel()
print("\nRavel Array:", ravel)
ravel[0] = 3
print("\nChanges directly happen in reshape array: \n",reshape) #original array change
print("\nFlatten: ", flatten) #flatten still doesn't change because flatten make copy 

#transopse matrix
transpose = reshape.T
print("\nTranspose: \n", transpose) 

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

Reshape Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Flatten Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

Ravel Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

Changes directly happen in reshape array: 
 [[ 3  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Flatten:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

Transpose: 
 [[ 3  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
